### PR TITLE
Update dev-requirements.txt pyre-extensions

### PR DESCRIPTION
**Pull request by ntlm1686**
I was unable to run any pyre command with pyre-extensions==0.0.21, but when I upgrade to 0.0.29, it works.
Dependencies are installed with `pip install -e '.[dev]'`.

When use `pyre` It throws the error below on both macos and linux:
```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/torchx-dev/bin/pyre", line 5, in <module>
    from pyre_check.client.pyre import main
  File "/opt/homebrew/Caskroom/miniforge/base/envs/torchx-dev/lib/python3.8/site-packages/pyre_check/client/pyre.py", line 19, in <module>
    from . import (
  File "/opt/homebrew/Caskroom/miniforge/base/envs/torchx-dev/lib/python3.8/site-packages/pyre_check/client/commands/__init__.py", line 6, in <module>
    from . import (  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401
  File "/opt/homebrew/Caskroom/miniforge/base/envs/torchx-dev/lib/python3.8/site-packages/pyre_check/client/commands/persistent.py", line 43, in <module>
    from . import (
  File "/opt/homebrew/Caskroom/miniforge/base/envs/torchx-dev/lib/python3.8/site-packages/pyre_check/client/commands/language_server_protocol.py", line 15, in <module>
    from pyre_extensions import override
ImportError: cannot import name 'override' from 'pyre_extensions' (/opt/homebrew/Caskroom/miniforge/base/envs/torchx-dev/lib/python3.8/site-packages/pyre_extensions/__init__.py)
```

Test plan:

### CODE REVIEW

**Comment by ljjsalt** [comment]
@d4l3k #587
